### ISSUE TITLE
显示Done但是依然报错

### ISSUE THREAD

**Issue by WJ-Lai** [Stephenfang51/VOC_to_COCO#1]
您好，我运行后您的代码后显示Done，但是同时也有报错的信息，请问是什么问题呢？

原始数据的目录（我用的是VOC2012）：
```
 VOC
    |-- Annotations
    		|-- 17125个xml
    |-- JPEGImages
    		|-- 17125张图片
    |-- ImageSets
    		|-- Action
    		|-- Layout
    		|-- Main
    		|-- Segmentation

 VOC_to_COCO
    |-- README.md
    |-- voc_to_coco.py
```
voc_to_coco.py中我只改了地址`voc_annotations = '/home/vincent/Data/VOCdevkit/VOC/Annotations/'`

生成的目录：
```
 VOC
    |-- Annotations
    		|-- 17125个xml
    |-- JPEGImages
    		|-- 17125张图片
    |-- ImageSets
    		|-- Action
    		|-- Layout
    		|-- Main
    		|-- Segmentation

 VOC_to_COCO
    |-- README.md
    |-- voc_to_coco.py

# 下面两个是新生成的

 VOC_COCO
    |-- annotations
    		|-- test2017.json
    		|-- val2017.json
    |-- images
    		|-- 17125张图片

 xml
    |-- xml_test
    		|-- 100个xml
    |-- xml_train
    		|-- 16925个xml
    |-- xml_val
    		|-- 100个xml
```

报错为：
```
/home/vincent/Data/VOCdevkit/VOC_COCO/ ----- folder created
/home/vincent/Data/VOCdevkit/VOC_COCO/images ----- folder created
/home/vincent/Data/VOCdevkit/VOC_COCO/annotations/ ----- folder created
/home/vincent/Data/VOCdevkit/xml/xml_val/ ----- folder created
/home/vincent/Data/VOCdevkit/xml/xml_test/ ----- folder created
/home/vincent/Data/VOCdevkit/xml/xml_train/ ----- folder created


 100 files copied to /home/vincent/Data/VOCdevkit/xml/xml_val/


***************************[ Done ! Go check your file ]****************************
Traceback (most recent call last):
  File "voc_to_coco.py", line 268, in <module>
    convert(xml_train_files, coco_json_annotations + 'train2017.json')
  File "voc_to_coco.py", line 231, in convert
    ymin = int(get_and_check(bndbox, "ymin", 1).text) - 1
ValueError: invalid literal for int() with base 10: '281.70000076293945'
```

我打开查看`test2017.json`和`val2017.json`，内容如下：
`test2017.json`内容：
```
images
    |-- 编号从0~99
type: "instances"
annotations
    |-- 编号从0~242
categories
    |-- 编号从0~19
```
`val2017.json`内容：
```
images
    |-- 编号从0~99
type: "instances"
annotations
    |-- 编号从0~199
categories
    |-- 编号从0~18
```

我修改了`voc_to_coco.py`中的`val_files_num`和`test_files_num`，尝试10或者1000，也是报同一个错误

我有以下的疑问：
1. 请问是不是应该还有一个关于train的json呢，因为报错的原因所以没有生成？
2. 请问有什么办法解决这个报错不？

谢谢！

**Comment by Stephenfang51** [comment]
> 您好，我运行后您的代码后显示Done，但是同时也有报错的信息，请问是什么问题呢？
> 
> 原始数据的目录（我用的是VOC2012）：
> 
> ```
>  VOC
>     |-- Annotations
>     		|-- 17125个xml
>     |-- JPEGImages
>     		|-- 17125张图片
>     |-- ImageSets
>     		|-- Action
>     		|-- Layout
>     		|-- Main
>     		|-- Segmentation
> 
>  VOC_to_COCO
>     |-- README.md
>     |-- voc_to_coco.py
> ```
> 
> voc_to_coco.py中我只改了地址`voc_annotations = '/home/vincent/Data/VOCdevkit/VOC/Annotations/'`
> 
> 生成的目录：
> 
> ```
>  VOC
>     |-- Annotations
>     		|-- 17125个xml
>     |-- JPEGImages
>     		|-- 17125张图片
>     |-- ImageSets
>     		|-- Action
>     		|-- Layout
>     		|-- Main
>     		|-- Segmentation
> 
>  VOC_to_COCO
>     |-- README.md
>     |-- voc_to_coco.py
> 
> # 下面两个是新生成的
> 
>  VOC_COCO
>     |-- annotations
>     		|-- test2017.json
>     		|-- val2017.json
>     |-- images
>     		|-- 17125张图片
> 
>  xml
>     |-- xml_test
>     		|-- 100个xml
>     |-- xml_train
>     		|-- 16925个xml
>     |-- xml_val
>     		|-- 100个xml
> ```
> 
> 报错为：
> 
> ```
> /home/vincent/Data/VOCdevkit/VOC_COCO/ ----- folder created
> /home/vincent/Data/VOCdevkit/VOC_COCO/images ----- folder created
> /home/vincent/Data/VOCdevkit/VOC_COCO/annotations/ ----- folder created
> /home/vincent/Data/VOCdevkit/xml/xml_val/ ----- folder created
> /home/vincent/Data/VOCdevkit/xml/xml_test/ ----- folder created
> /home/vincent/Data/VOCdevkit/xml/xml_train/ ----- folder created
> 
> 
>  100 files copied to /home/vincent/Data/VOCdevkit/xml/xml_val/
> 
> 
> ***************************[ Done ! Go check your file ]****************************
> Traceback (most recent call last):
>   File "voc_to_coco.py", line 268, in <module>
>     convert(xml_train_files, coco_json_annotations + 'train2017.json')
>   File "voc_to_coco.py", line 231, in convert
>     ymin = int(get_and_check(bndbox, "ymin", 1).text) - 1
> ValueError: invalid literal for int() with base 10: '281.70000076293945'
> ```
> 
> 我打开查看`test2017.json`和`val2017.json`，内容如下：
> `test2017.json`内容：
> 
> ```
> images
>     |-- 编号从0~99
> type: "instances"
> annotations
>     |-- 编号从0~242
> categories
>     |-- 编号从0~19
> ```
> 
> `val2017.json`内容：
> 
> ```
> images
>     |-- 编号从0~99
> type: "instances"
> annotations
>     |-- 编号从0~199
> categories
>     |-- 编号从0~18
> ```
> 
> 我修改了`voc_to_coco.py`中的`val_files_num`和`test_files_num`，尝试10或者1000，也是报同一个错误
> 
> 我有以下的疑问：
> 
> 1. 请问是不是应该还有一个关于train的json呢，因为报错的原因所以没有生成？
> 2. 请问有什么办法解决这个报错不？
> 
> 谢谢！

您好

看起来像是在xml中的ymin的数值有问题， python在转换成int类型的报错
您这个数据集之前有训练过没问题吗？

或者可以修改如下试试

voc_to_coco.py 第231行
将
```
ymin = int(get_and_check(bndbox, "ymin", 1).text) - 1
```

修改为

```
ymin = int(float(get_and_check(bndbox, "ymin", 1).text)) - 1
```

**Comment by WJ-Lai** [comment]
@Stephenfang51 
您好，确实是数据的原因，其他正常的数据里面都是整数，报错的xml中ymin是一个浮点数，所以转换int类型的时候报错。您推荐的修改方案可行！谢谢！

但是我对代码的细节还存在一些疑问，想和您请教一下：
1. 为什么提取xmin和ymin后要减一呢？
2. 如果230行~233行不转换为int类型，而是全部用float()的话（例如改为`ymin = float(get_and_check(bndbox, "ymin", 1).text)`），可以更少地丢失原始标注的信息。而且我看COCO的注释（`instances_val2017.json`中`annotations`的`bbox`也是采用float类型）
请问是什么原因要选择int呢？

**Comment by Stephenfang51** [comment]
> @Stephenfang51
> 您好，确实是数据的原因，其他正常的数据里面都是整数，报错的xml中ymin是一个浮点数，所以转换int类型的时候报错。您推荐的修改方案可行！谢谢！
> 
> 但是我对代码的细节还存在一些疑问，想和您请教一下：
> 
> 1. 为什么提取xmin和ymin后要减一呢？
> 2. 如果230行~233行不转换为int类型，而是全部用float()的话（例如改为`ymin = float(get_and_check(bndbox, "ymin", 1).text)`），可以更少地丢失原始标注的信息。而且我看COCO的注释（`instances_val2017.json`中`annotations`的`bbox`也是采用float类型）
>    请问是什么原因要选择int呢？

您好， 不好意思回的晚了

那个部分的代码我有附上原作者的来源

具体怎么生成的我就没有细看了^_^

那么我个人的看法觉得坐标点后面的小数不会导致显著的差异， 太细了

**Comment by WJ-Lai** [comment]
@Stephenfang51 好的明白了，您的代码对我帮助很大，非常感谢！
